// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUTNt3G9hB_YuEniSvqQLjfuBtZa_v08k',
    appId: '1:197351301825:web:a02df3122fcf217c622a40',
    messagingSenderId: '197351301825',
    projectId: 'egyptian-american-tv',
    authDomain: 'egyptian-american-tv.firebaseapp.com',
    storageBucket: 'egyptian-american-tv.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5r1mF_g-8P7gE8BiexE5Nzfbn_RKWwaU',
    appId: '1:197351301825:android:10d621e7ee778b4e622a40',
    messagingSenderId: '197351301825',
    projectId: 'egyptian-american-tv',
    storageBucket: 'egyptian-american-tv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH8MUmQDZICujO5SXB2T1tiDCwvTNs1t0',
    appId: '1:197351301825:ios:0bd8881fb5127e54622a40',
    messagingSenderId: '197351301825',
    projectId: 'egyptian-american-tv',
    storageBucket: 'egyptian-american-tv.appspot.com',
    iosClientId: '197351301825-6dive0f94qn0dngo4fac728badmbhqrl.apps.googleusercontent.com',
    iosBundleId: 'com.example.egyptianAmericanTv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH8MUmQDZICujO5SXB2T1tiDCwvTNs1t0',
    appId: '1:197351301825:ios:0bd8881fb5127e54622a40',
    messagingSenderId: '197351301825',
    projectId: 'egyptian-american-tv',
    storageBucket: 'egyptian-american-tv.appspot.com',
    iosClientId: '197351301825-6dive0f94qn0dngo4fac728badmbhqrl.apps.googleusercontent.com',
    iosBundleId: 'com.example.egyptianAmericanTv',
  );
}
